

export const FlagMap: { [key: string]: string } = {
    "ARG": "🇦🇷",
    "AUS": "🇦🇺",
    "AUT": "🇦🇹",
    "BEL": "🇧🇪",
    "CAN": "🇨🇦",
    "CHI": "🇨🇱",
    "CHN": "🇨🇳",
    "COL": "🇨🇴",
    "DEN": "🇩🇰",
    "ENG": "🇬🇧",
    "ESP": "🇪🇸",
    "FRA": "🇫🇷",
    "GER": "🇩🇪",
    "IND": "🇮🇳",
    "IRL": "🇮🇪",
    "ITA": "🇮🇹",
    "JPN": "🇯🇵",
    "KOR": "🇰🇷",
    "MEX": "🇲🇽",
    "NIR": "🏴󠁧󠁢󠁮󠁩󠁲󠁿",
    "NOR": "🇳🇴",
    "NZL": "🇳🇿",
    "POL": "🇵🇱",
    "POR": "🇵🇹",
    "RSA": "🇿🇦",
    "SCO": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "SVK": "🇸🇰",
    "SWE": "🇸🇪",
    "THA": "🇹🇭",
    "TPE": "🇹🇼",
    "USA": "🇺🇸",
    "VEN": "🇻🇪",
    "WAL": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "ZIM": "🇿🇼"
}